/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BattleContract1__factory } from "./BattleContract1__factory";
export { Lock__factory } from "./Lock__factory";
