/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BattleContract1 } from "./BattleContract1";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { BattleContract1__factory } from "./factories/BattleContract1__factory";
export { Lock__factory } from "./factories/Lock__factory";
